# Site settings
alert-message: ' and <a href="http://getbootstrap.com" class="alert-link">http://getbootstrap.com</a>.'
category-list: [Widgets, Layouts]
company: 'Red Hat&reg;'
title: 'Red Hat&reg; Common User Experience'
title-product: 'Red Hat&reg; Common User Experience'
url-components: '../components/patternfly/components/'
url-css-extra: 'tests.css'
url-css-main: '../dist/css/rcue.min.css'
url-img: 'img/'
url-jquery: '//code.jquery.com/jquery-1.10.2.min.js'
url-js: '../components/patternfly/dist/js/patternfly.min.js'